/**
 * Shared data types for static portfolio content.
 *
 * These types mirror what was previously generated by Prisma. They are kept
 * loose-but-precise on purpose so that the same structures used to live in the
 * Postgres database can be expressed as plain TypeScript modules.
 */

export type Category =
  | "FRONTEND"
  | "FRONTEND_LIBRARY"
  | "BACKEND"
  | "RUNTIME_LANGUAGE"
  | "FRAMEWORK_API"
  | "DATA_AUTH"
  | "VALIDATION_SECURITY"
  | "CLOUD_INFRA"
  | "MERMAID_CORE"
  | "MERMAID_TEST_QUALITY"
  | "MERMAID_BUILD_WORKFLOW"
  | "AI_MODEL"
  | "AI_AGENT"
  | "AI_INFRA"
  | "KKINI_AI_SERVER"
  | "KKINI_CHATBOT"
  | "KKINI_APP"
  | "INFRA_TEST"
  | "ENV"
  | "DESIGN"
  | "ETC";

export interface Skill {
  id: number;
  category: Category;
  items: string[];
  item: string;
  blobUrl: string;
}

export interface Intro {
  id: number;
  title: string;
  detail: string;
  blobUrl: string | null;
}

export interface Blog {
  id: number;
  title: string;
  date: string;
  forwardLink: string;
  bgImageUrl: string;
}

export interface ExperienceLink {
  label: string;
  href: string;
}

export interface PdfDocumentSection {
  label: string;
  startPage: number;
  endPage: number;
}

export interface ExperienceDetailMedia {
  src: string;
  alt: string;
  width: number;
  height: number;
  href?: string;
  linkLabel?: string;
  maxWidth?: number;
  placement?: "top" | "bottom" | "left" | "right";
  /** 좌/우 배치일 때 본문과의 가로 간격(px) — 기본 16 */
  gap?: number;
  /** 이미지가 카드를 가득 채우도록 자를 때 사용하는 프레임 비율 */
  frameAspectRatio?: string;
  /** 여러 이미지를 나란히 놓을 때 원본 비율과 관계없이 같은 너비로 배치 */
  equalWidth?: boolean;
  /** "circle"이면 정사각형으로 잘라 원형으로 렌더 */
  shape?: "circle";
  /** 이미지 아래에 붙는 짧은 설명 — 링크가 있으면 링크처럼 보인다 */
  caption?: string;
}

// A PDF attached to a single detail section, with its own viewer TOC.
// (The legacy path — `showPdf` + the experience-level `links`/`pdfSections` —
// still works for experiences with a single PDF, e.g. the Mermaid entry.)
export interface ExperienceDetailPdf {
  href: string;
  label: string;
  sections?: PdfDocumentSection[];
  /** 버튼 강조색 */
  tone?: "default" | "green" | "blue";
  /** 버튼 정렬 — 기본 왼쪽 */
  align?: "left" | "right";
  /** true면 버튼을 extra 블록과 같은 줄 오른쪽에 배치 (텍스트가 좁아져 줄바꿈됨) */
  inline?: boolean;
}

// 섹션의 이미지 슬롯 — 배열로 주면 한 줄에 나란히 놓인다.
// 폭은 각 이미지의 가로세로 비율대로 나뉘어 높이가 서로 맞춰지고,
// 줄 전체의 placement와 maxWidth는 첫 이미지의 값을 따른다.
export type ExperienceSectionMedia = ExperienceDetailMedia | ExperienceDetailMedia[];

// 앱 마켓 설치 링크 — 섹션 본문 아래에 스토어 배지 버튼으로 렌더된다.
export interface ExperienceStoreLink {
  store: "appstore" | "playstore";
  href: string;
}

// 섹션 본문에 넣는 간단한 표 — 셀 텍스트에도 highlights가 적용된다.
export interface ExperienceDetailTable {
  headers: string[];
  rows: string[][];
}

export interface ExperienceDetailAction {
  title: string;
  period?: string;
  description: string;
  label?: string;
  /** extra 본문 앞에 카드가 필요한 경우에만 사용 */
  position?: "beforeExtra" | "afterExtra";
  tone?: "yellow" | "green";
  /** 활동 카드 아래에 이어지는 짧은 회고 문단 */
  afterText?: string;
  afterHighlights?: string[];
  href?: string;
  modalName?: string;
  modalImages?: string[];
}

// 섹션 본문 뒤에 이어 붙는 보조 블록.
export interface ExperienceDetailExtra {
  /** 블록 맨 위(이미지보다 위)에 오는 소제목 */
  heading?: string;
  items: string[];
  highlights?: string[];
  layout?: "list" | "paragraphs";
  media?: ExperienceSectionMedia;
  /** false로 두면 앞 블록과 구분선 없이 이어서 렌더 (기본 true) */
  divider?: boolean;
}

export interface ExperienceDetailSection {
  title: string;
  items: string[];
  highlights?: string[];
  layout?: "list" | "paragraphs";
  media?: ExperienceSectionMedia;
  /** 본문 아래 한 줄로 강조하는 슬로건 — 따옴표와 강조색이 자동으로 붙는다 */
  slogan?: string;
  /** 본문 끝에 붙는 앱 마켓 설치 버튼 (media가 좌/우면 텍스트 칼럼 안에 들어간다) */
  storeLinks?: ExperienceStoreLink[];
  /** items 아래에 렌더되는 표 */
  table?: ExperienceDetailTable;
  /** 배열로 주면 여러 덩어리가 순서대로 이어져, 문단·이미지·문단처럼 엮을 수 있다 */
  extra?: ExperienceDetailExtra | ExperienceDetailExtra[];
  pdf?: ExperienceDetailPdf;
  /** 소재별 문서 목록 — 카드형 버튼 리스트로 쌓이고, 각각 뷰어(.md는 MD 모달)로 열린다 */
  docs?: ExperienceDetailPdf[];
  /** 외부 링크 또는 레거시 프로젝트 모달로 이어지는 활동 카드 */
  actions?: ExperienceDetailAction[];
  showPdf?: boolean;
  /** true면 경험의 subDetails 아코디언을 이 섹션 안에 렌더 (패널 하단 대신) */
  showSubDetails?: boolean;
  /** subDetails 카드를 펼치지 않고 연결된 문서 모달로 바로 열기 */
  subDetailsMode?: "accordion" | "modal";
}

// A deep-dive card nested inside an experience's detail panel — rendered as an
// accordion below the main sections (e.g. the SureSoftTech sub-projects).
export interface ExperienceSubDetail {
  id: string;
  title: string;
  /** 아코디언 강조 테두리 색 — 기본 노랑 */
  tone?: "yellow" | "green" | "blue";
  /** 아코디언을 열었을 때 본문 최상단에서 지연 로드할 대표 이미지 */
  media?: ExperienceDetailMedia;
  sections: ExperienceDetailSection[];
  /** 카드 본문 끝에 배치하는 마무리 회고 문단 */
  afterText?: string;
  afterHighlights?: string[];
}

export interface Experience {
  id: number;
  title: string;
  period: string;
  /** 카드 왼쪽 타임라인에서 기간을 숨길 때 사용 */
  hidePeriod?: boolean;
  items: string[];
  links: ExperienceLink[];
  pdfSections?: PdfDocumentSection[];
  detailSections?: ExperienceDetailSection[];
  subDetails?: ExperienceSubDetail[];
  is_active: boolean | null;
  sub_title: string | null;
  imageUrl?: string;
  /** 대표 이미지 슬롯의 배경색 */
  imageBackgroundColor?: string;
  /** 콘텐츠를 나중에 채울 카드에서 이미지·기술 스택 영역을 빈 슬롯으로 유지 */
  placeholderSlots?: boolean;
  index: number;
  skill_ids: number[];
  category: string | null;
}

// A curated project case, shown as an inline accordion (problem → approach → result).
export interface ProjectCase {
  id: string;
  company: string;
  period: string;
  title: string;
  summary: string;
  points: string[];
  stack: string[];
  links?: ExperienceLink[];
}

export interface Education {
  id: number;
  title: string;
  sub_title: string;
  period: string;
  items: string[];
  category: string | null;
}
