/**
 * Shared data types for static portfolio content.
 *
 * These types mirror what was previously generated by Prisma. They are kept
 * loose-but-precise on purpose so that the same structures used to live in the
 * Postgres database can be expressed as plain TypeScript modules.
 */

export type Category =
  | "FRONTEND"
  | "FRONTEND_LIBRARY"
  | "BACKEND"
  | "RUNTIME_LANGUAGE"
  | "FRAMEWORK_API"
  | "DATA_AUTH"
  | "VALIDATION_SECURITY"
  | "CLOUD_INFRA"
  | "MERMAID_CORE"
  | "MERMAID_TEST_QUALITY"
  | "MERMAID_BUILD_WORKFLOW"
  | "INFRA_TEST"
  | "ENV"
  | "DESIGN"
  | "ETC";

export interface Skill {
  id: number;
  category: Category;
  items: string[];
  item: string;
  blobUrl: string;
}

export interface Intro {
  id: number;
  title: string;
  detail: string;
  blobUrl: string | null;
}

export interface Blog {
  id: number;
  title: string;
  date: string;
  forwardLink: string;
  bgImageUrl: string;
}

export interface ExperienceLink {
  label: string;
  href: string;
}

export interface PdfDocumentSection {
  label: string;
  startPage: number;
  endPage: number;
}

export interface ExperienceDetailMedia {
  src: string;
  alt: string;
  width: number;
  height: number;
  href?: string;
  linkLabel?: string;
  maxWidth?: number;
  placement?: "top" | "left" | "right";
}

// A PDF attached to a single detail section, with its own viewer TOC.
// (The legacy path — `showPdf` + the experience-level `links`/`pdfSections` —
// still works for experiences with a single PDF, e.g. the Mermaid entry.)
export interface ExperienceDetailPdf {
  href: string;
  label: string;
  sections?: PdfDocumentSection[];
  /** 버튼 정렬 — 기본 왼쪽 */
  align?: "left" | "right";
  /** true면 버튼을 extra 블록과 같은 줄 오른쪽에 배치 (텍스트가 좁아져 줄바꿈됨) */
  inline?: boolean;
}

export interface ExperienceDetailSection {
  title: string;
  items: string[];
  highlights?: string[];
  layout?: "list" | "paragraphs";
  media?: ExperienceDetailMedia;
  extra?: {
    items: string[];
    highlights?: string[];
    layout?: "list" | "paragraphs";
    media?: ExperienceDetailMedia;
    /** false로 두면 본문과 extra 사이 구분선 없이 이어서 렌더 (기본 true) */
    divider?: boolean;
  };
  pdf?: ExperienceDetailPdf;
  showPdf?: boolean;
}

// A deep-dive card nested inside an experience's detail panel — rendered as an
// accordion below the main sections (e.g. the SureSoftTech sub-projects).
export interface ExperienceSubDetail {
  id: string;
  title: string;
  sections: ExperienceDetailSection[];
}

export interface Experience {
  id: number;
  title: string;
  period: string;
  items: string[];
  links: ExperienceLink[];
  pdfSections?: PdfDocumentSection[];
  detailSections?: ExperienceDetailSection[];
  subDetails?: ExperienceSubDetail[];
  is_active: boolean | null;
  sub_title: string | null;
  imageUrl?: string;
  index: number;
  skill_ids: number[];
  category: string | null;
}

// A curated project case, shown as an inline accordion (problem → approach → result).
export interface ProjectCase {
  id: string;
  company: string;
  period: string;
  title: string;
  summary: string;
  points: string[];
  stack: string[];
  links?: ExperienceLink[];
}

export interface Education {
  id: number;
  title: string;
  sub_title: string;
  period: string;
  items: string[];
  category: string | null;
}
